version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - echo Installing Docker...
      - yum install -y docker
      - service docker start
      - systemctl enable docker

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 445567078150.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=445567078150.dkr.ecr.us-east-1.amazonaws.com/demo-app

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating image in Kubernetes...
      - aws eks update-kubeconfig --region us-east-1 --name demo-cluster
      - kubectl set image deployment/demo-app demo-app=$REPOSITORY_URI:$IMAGE_TAG
      - kubectl rollout status deployment/demo-app

  post_build:
    commands:
      - echo Build and deployment completed successfully.

artifacts:
  files:
    - imagedefinitions.json  # optional
