version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Configuring access to EKS...
      - aws eks update-kubeconfig --region us-east-1 --name demo-cluster

  build:
    commands:
      - echo Triggering rollout restart...
      - kubectl rollout restart deployment/demo-app
      - kubectl rollout status deployment/demo-app
