version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Configuring access to EKS...
      - export AWS_REGION=us-east-1
      - export AWS_DEFAULT_REGION=us-east-1
      - export KUBECONFIG=$HOME/.kube/config
      - mkdir -p $HOME/.kube
      - aws eks update-kubeconfig --region $AWS_REGION --name demo-cluster
      - aws sts get-caller-identity

  build:
    commands:
      - echo Testing cluster access...
      - kubectl get nodes
      - echo Restarting deployment...
      - kubectl rollout restart deployment/demo-app
      - kubectl rollout status deployment/demo-app
      - echo Generating imagedefinitions.json...
      - echo '[{"name":"demo-app","imageUri":"dummy"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
