version: 0.2

env:
  variables:
    AWS_REGION:   us-east-1
    ACCOUNT_ID:   "445567078150"
    REPO_NAME:    demo-app
    CLUSTER_NAME: demo-cluster
  exported-variables:
    - IMAGE_TAG
    - IMAGE_URI

phases:
  install:           # nothing to do – CodeBuild managed image has Docker running
    commands: []

  pre_build:
    commands:
      - echo "🔑  Logging in to ECR…"
      - aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - export IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo "🏷️  IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - docker build --no-cache -t $IMAGE_URI .
      - docker push  $IMAGE_URI

  post_build:
    commands:
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - kubectl set image deployment/demo-app demo-app=$IMAGE_URI --record
      - kubectl rollout status deployment/demo-app
      - echo "✅  Deployment complete"
